name: Monthly Data Ingestion

on:
  schedule:
    # Run at 03:00 UTC on the 3rd of every month
    - cron: "0 3 3 * *"
  workflow_dispatch:  # allows you to run manually from GitHub Actions

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb requests pandas

      - name: Run ingestion script
        run: |
          python scripts/ingest.py --db poke.duckdb --month $(date +'%Y-%m')
